from .base import ModelProvider


class MockProvider(ModelProvider):
    """Fake provider for testing the wake loop without any API key."""

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        if "YOUR TASK RIGHT NOW: REFLECT" in system_prompt:
            # This is the reflection pass.
            for section in ["IDENTITY", "RULES", "CURRENT KNOWLEDGE", "OPEN COMMITMENTS"]:
                assert section in system_prompt, f"Reflection prompt missing: {section}"
            return (
                "Nothing has changed since there's no prior record — this "
                "is effectively a first wake. No recurring pattern to name "
                "yet. Identity fields are still template placeholders, "
                "which is honest given no real work has happened. Most "
                "useful focus: confirm the loop runs correctly and record "
                "an honest baseline rather than inventing progress. "
                "(This is a mock reflection for testing.)"
            )

        # This is the journal pass — should receive the reflection back,
        # plus rules and the capability boundary, but NOT the raw
        # identity/index/commitments sections again (those were already
        # synthesized in the reflection).
        assert "YOUR REFLECTION THIS WAKE" in system_prompt, \
            "Journal prompt missing reflection section"
        assert "CAPABILITY BOUNDARY" in system_prompt, \
            "Journal prompt missing capability boundary"
        return (
            "## What I did\n"
            "This is a mock response confirming the two-pass wake loop "
            "(reflect, then journal) executed correctly end-to-end.\n\n"
            "## What I decided\n"
            "N/A — test run.\n\n"
            "## Commitments touched\n"
            "None.\n\n"
            "## Uncertainties / flags\n"
            "This is a test entry generated by MockProvider, not a real model."
        )
