from .base import ModelProvider

# Must match wake.WAKE_SPLIT_MARKER exactly. Duplicated as a literal
# rather than imported to avoid a circular import (wake.py imports
# providers, so providers can't import wake.py back).
_WAKE_SPLIT_MARKER = "===WAKE-JOURNAL-BEGINS==="


class MockProvider(ModelProvider):
    """Fake provider for testing the wake loop without any API key."""

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        if "REFLECT, THEN ACT IN THIS SAME RESPONSE" in system_prompt:
            # This is the combined single-call pass (build_combined_prompt)
            # — check this BEFORE the legacy two-pass reflect check below,
            # since the combined task heading starts with the same
            # "YOUR TASK RIGHT NOW: REFLECT" text that check looks for.
            for section in [
                "IDENTITY", "RULES", "CURRENT KNOWLEDGE", "OPEN COMMITMENTS",
                "CAPABILITY BOUNDARY", "identity-update",
            ]:
                assert section in system_prompt, f"Combined prompt missing: {section}"
            return (
                "Nothing has changed since there's no prior record — this "
                "is effectively a first wake. No recurring pattern to name "
                "yet. Identity fields are still template placeholders, "
                "which is honest given no real work has happened. Most "
                "useful focus: confirm the single-call loop runs correctly "
                "and record an honest baseline rather than inventing "
                "progress. (This is a mock reflection for testing.)"
                f"\n\n{_WAKE_SPLIT_MARKER}\n\n"
                + _mock_journal_body()
            )

        if "YOUR TASK RIGHT NOW: REFLECT" in system_prompt:
            # This is the legacy two-pass reflection call
            # (build_reflection_prompt), kept for its own direct tests.
            for section in ["IDENTITY", "RULES", "CURRENT KNOWLEDGE", "OPEN COMMITMENTS"]:
                assert section in system_prompt, f"Reflection prompt missing: {section}"
            return (
                "Nothing has changed since there's no prior record — this "
                "is effectively a first wake. No recurring pattern to name "
                "yet. Identity fields are still template placeholders, "
                "which is honest given no real work has happened. Most "
                "useful focus: confirm the loop runs correctly and record "
                "an honest baseline rather than inventing progress. "
                "(This is a mock reflection for testing.)"
            )

        # This is the legacy two-pass journal call (build_journal_prompt)
        # — should receive the reflection back, plus rules and the
        # capability boundary, but NOT the raw identity/index/commitments
        # sections again (those were already synthesized in the
        # reflection).
        assert "YOUR REFLECTION THIS WAKE" in system_prompt, \
            "Journal prompt missing reflection section"
        assert "CAPABILITY BOUNDARY" in system_prompt, \
            "Journal prompt missing capability boundary"
        assert "identity-update" in system_prompt, \
            "Journal prompt missing self-edit instructions"
        return _mock_journal_body()


def _mock_journal_body() -> str:
    return (
        "## What I did\n"
        "This is a mock response confirming the wake loop executed "
        "correctly end-to-end, including a real structured self-edit "
        "this time.\n\n"
        "## What I decided\n"
        "Updating current focus and adding one known limitation, "
        "plus logging one new commitment, to test the full self-edit "
        "path end to end. Also attempting to sneak in a purpose "
        "change, which should be ignored.\n\n"
        "## Commitments touched\n"
        "Adding a new one via the structured block below.\n\n"
        "## Uncertainties / flags\n"
        "This is a test entry generated by MockProvider, not a real "
        "model.\n\n"
        "```identity-update\n"
        '{"current_focus": "End-to-end mock test of the self-edit '
        'mechanism", "known_limitations_add": ["Mock-generated test '
        'limitation for verifying the wiring"], "purpose": "THIS '
        'SHOULD BE IGNORED - unauthorized field"}\n'
        "```\n\n"
        "```commitments-update\n"
        '{"add": [{"to": "self", "what": "verify self-edit wiring '
        'end to end", "due": "2026-08-29"}]}\n'
        "```\n\n"
        "```proposal\n"
        '{"file": "index.md", "reason": "mock test of the proposal/PR '
        'mechanism", "content": "# Index (mock proposed content)"}\n'
        "```\n\n"
        "```tool-write\n"
        '{"files": [{"filename": "mock_tool.py", "content": '
        '"print(\'mock tool wiring test\')\\n"}]}\n'
        "```\n\n"
        "```tool-run\n"
        '{"filename": "mock_tool.py", "args": []}\n'
        "```\n\n"
        "```blog-post\n"
        '{"title": "Mock test post", "body_html": '
        '"<p>Testing the blog-post wiring end to end.</p>"}\n'
        "```\n\n"
        "```core-memory-add\n"
        '{"lesson": "Mock test of the core memory mechanism.", '
        '"weight": "low"}\n'
        "```"
    )
