from .base import ModelProvider


class MockProvider(ModelProvider):
    """Fake provider for testing the wake loop without any API key."""

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        # Sanity-check that the context assembly actually worked —
        # fail loudly if expected sections are missing.
        required = ["IDENTITY", "RULES", "CURRENT KNOWLEDGE", "OPEN COMMITMENTS"]
        for section in required:
            assert section in system_prompt, f"Missing section: {section}"

        return (
            "## What I read this wake\n"
            "identity.md, rules.md, index.md, open commitments\n\n"
            "## What I did\n"
            "This is a mock response confirming the wake loop executed "
            "correctly end-to-end.\n\n"
            "## What I decided\n"
            "N/A — test run.\n\n"
            "## Commitments touched\n"
            "None.\n\n"
            "## Uncertainties / flags\n"
            "This is a test entry generated by MockProvider, not a real model."
        )
